### ISSUE TITLE
Ticket Delivery Integration

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#272]
Depends on #301

This issue will modify the existing ticket checkout user flow, both on the frontend and backend.

Below is a more detailed breakdown of the tasks at hand

Code changes:
- [ ] Reconcile differences between ticket utility classes (naming, method interface, etc.) (#315)

UPDATE:
These 3 tasks will be done in a future sprint (as apart of overhauling checkout)
- [ ] Normalize Google class ID's for google ticket. (Both `Event` and `Ticket` need a `google_class_id` field) (#323)
- [ ] New Confirmation API endpoint for ticket delivery (uses celery for email) (depends on #316)
- [ ] Replace success screen with new page (depends on #316)
