### ISSUE TITLE
Overhaul Documentation

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#288]
Root level README with 
- [x] Database ERD (static image for now, will research later) - @hubertokf  (#338)
- [x] Project architecture diagram - @hubertokf   (#338)
- [x] Infrastructure diagram - @hubertokf  (#338)

Project-Level README (setup, basic overview, etc.)
- [x] /backend (already exists)
- [x] /frontend/eventportal (#303)
- [x] frontend/scanner-app (@halfmoonui)

Backend App-Level README with User Flows and functional / non-functional requirements
- [ ] /backend/apps/root (@crypto-rizzo)
- [x] /backend/apps/api_checkoutportal (will be done at later date with #316)
- [x] /backend/apps/api_scanner (@devjoaov) (#304/#305)
- [x] /backend/apps/dashboard (@halfmoonui) (#310)
- [x] /backend/apps/event_discovery (@halfmoonui) (#309)

Github Wiki with 
- [x] User Stories
- [x] Design Documents
- [x] Research, etc
