### ISSUE TITLE
Minor Event Form Improvements

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#401]
Documenting minor event form issues here. I don't think these are high priority, but should be tackled at some point

# Part 1
- [ ] No way to easily delete date/time fields (at least on safari). Maybe a JS reset button would be nice?
- [ ] More human-readable timezones
- [ ] Image preview for image upload
