### ISSUE TITLE
Pudgy Checklist

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#567]
- [x] Whitelabel correct accounts: https://rulimio.slack.com/archives/C0492RJFYTW/p1675886888907959
- [x] Ensure timezones across the board are being handled correctly. This is an international event with likely many attendees traveling across timezones (as well as organizers)
- [ ] Add timezone / duration to checkout app
- [x] #562  (we need to ensure correct link is being shared as this will be one of our first public showings)
- [x] timezone / duration ui in checkout app
