### ISSUE TITLE
Master Issue: UX Improvements

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#656]
# General
- [x] Consider page for viewing some events? Either featured or past? _**(I remember we decided against this because it shows spam/test events most of the time. For featured, we don't have enough volume yet...)**_
- [x] improve team image and banner image display / cropping (checkout pages and dashboard pages)

# Team Creation
- [x] Either create default team or have user only fill in team name...(think twitter flow where only username is required, and then description ++ picture are optional and set to some default)

# Event Form Step One 
- [ ] Consider splitting page 1 of event form into two forms
- [x] team name vs organizer name (remove organizer name?)
- [x] add loading icon on go live page (request can take time because of google API)
- [ ] tweak go live page design (possibly revert to original design)

# Event Form Step Two (Ticket Tier Form)
- [x] Remove asset type 
- [x] Reconsider other NFT fields _**(Please elaborate)**_
- [x] Better help text on ticker tier form _**(Please elaborate/provide specific help text if possible)**_
