### ISSUE TITLE
Internal Release MVP Checklist

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#68]
Master Issue for internal release MVP 

Infrastructure
- [x] Deployed Customer Dashboard, available at <domain>
- [x] Deployed Event Portal, available at <domain>/<shareable_slug>
- [x] Deployed Ticker Scanner, available at <domain>/<shareable_slug>

Subtasks
- [x] close #47
