### ISSUE TITLE
Final Event Portal Checklist

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#84]
# General
- [x] Update .env with dashboard URL
- [x] Update success page with ticket download URL

# UI
## Container
- [x] 600px wide maximum (max width 100%)
- [x] No border radius equal or below mobile breakpoint (576px)
- [x] Centered vertically and horizontally on all screen sizes
- [ ] Footer content should align with main content (horizontally)
- [x] Container height / width should remain consistent across pages

## Landing Page
- [x] CTA Font Size too small (at least 8-10px more) and should also be 700 font weight
- [x] In 12-column bootstrap format, left-side content should take 7, and button should take 4 (with offset of 1). Currently content is too small and button is too big
- [x] Capacity info should not be full-width of content
- [x] Increased Vertical margin between date and location
- [x] Date and Location icons should have 5px space between related text
- [x] Decrease space between event Title and event description
- [ ] Team Info and Team picture should align with main content below (left-hand side)
- [ ] Team image should align vertically with cover photo exactly at halfway point
- [x] Team Info and Team picture should be closer together horizontally

## Ticket Selection 
- [x] Checkout cart sidebar should be lighter gray (#F6F7F9)
- [x] Ticket selection dropdown should be smaller
- [ ] Ticket selection arrow same size as number, with both aligned on left-hand and right-hand side, respectively (10px left, 10px right for example)
- [x] Decrease size between Title and subtitle across page (maximum of 15px)
- [x] On mobile screen, ticket selection dropdown should become full-width (similar to continue button)

## Checkout Selection
- [x] wallet cards into radio buttons -> they are not on radio buttons but it's with the same logic
- [x] Wallet cards default grayscale, selected one is color
- [x] Call to action “Checkout” button is disabled until wallet radio button is selected
- [x] Images should be SVG’s
- [x] No text overflow for walletconnect (font size smaller if needed)
- [x] More spacing inside “Proof of NFT Ownership” container
- [x] On mobile, wallet cards should be full-width 
- [x] Remove placeholder text in white

## Loading Component
- [x] Bigger Title

## Checkout Status
- [x] Update to match figma
