### ISSUE TITLE
Final Ticket Scanner Checklist

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#85]
- [x] update .env for dashboard URL (@crypto-rizzo )

When added the halfmoon template, the alignments in the following screens broke and must addressed before the demo internal release:
- [x] scanner UI

General issues (I think they don't block the demo since it is functional the way it is):
- [ ] Toast (persist until closed or next toast is rendered). It is currently vanishing too fast.
- [x] Related to toasts, scans should not happen in succession unless the QR code value has changed. (When hovering on QR code, multiple scans happen)
- [x] Invalid landing page (on event 404/403, there must be an error page informing the user to get the proper scanner link from the scanner dashboard)
- [x] At capacity page happens a bit too quickly. Similar to toast, navigating too fast on the last ticket scan. Additionally, this page should mirror the landing page UI-wise. Current is a bit bland and resembles an error page too much with the big red X
- [x] error pages UI (@mvpedro)
- [x] Ticket capacity should be based on the event capacity, not how many tickets issued (if event is for 100 people, and no tickets have been issued, should be 0/100 for the ticket scanner)
