### ISSUE TITLE
Final Dashboard Checklist

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#86]
- [x] Links to scanner and event portal from dashboard - @NicoRyberg 
- [x] Update .env with portal / scanner URL
- [ ] Error handling of 500 pages on form create
- [ ] Tooltips and info where available
