### ISSUE TITLE
External Release MVP Checklist

### ISSUE THREAD

**Issue by slayb3ar** [SocialPass/socialpass#90]
Infrastructure
- [x] Deployed Customer Dashboard, available at dashboard.socialpass.io
- [x] Deployed Event Portal, available at tickets.socialpass.io
- [x] Deployed Ticker Scanner, available at scanner.socialpass.io/

Security
- [x] Reconfigure all environment variables for staging and production

Accounts
- [x] Upgrade Mailgun 
- [x] Configure Mailgun

Subtasks
- [x] Close #20
- [x] Merge #94
- [x] Merge #97
- [x] Merge #98
- [x] Merge #96
